[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
include_trailing_comma = true
multi_line_output = 3
skip = [
    "third_party",
]
skip_gitignore = true
use_parentheses = true
