// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <c10/util/Exception.h>
#include <c10/macros/Macros.h>
#include <hip/hip_runtime.h>

// Note [CHECK macro]
// ~~~~~~~~~~~~~~~~~~
// This is a macro so that AT_ERROR can get accurate __LINE__
// and __FILE__ information.  We could split this into a short
// macro and a function implementation if we pass along __LINE__
// and __FILE__, but no one has found this worth doing.

// For HIP Runtime API
#define C10_HIP_CHECK(EXPR)                                         \
  do {                                                               \
    hipError_t __err = EXPR;                                        \
    if (__err != hipSuccess) {                                      \
      auto error_unused C10_UNUSED = hipGetLastError();             \
      TORCH_CHECK(false, "HIP error: ", hipGetErrorString(__err)); \
    }                                                                \
  } while (0)

  #define C10_HIP_CHECK_WARN(EXPR)                            \
  do {                                                         \
    hipError_t __err = EXPR;                                  \
    if (__err != hipSuccess) {                                \
      auto error_unused C10_UNUSED = hipGetLastError();       \
      TORCH_WARN("HIP warning: ", hipGetErrorString(__err)); \
    }                                                          \
  } while (0)

// This should be used directly after every kernel launch to ensure
// the launch happened correctly and provide an early, close-to-source
// diagnostic if it didn't.
#define C10_HIP_KERNEL_LAUNCH_CHECK() C10_HIP_CHECK(hipGetLastError())
