// !!! This is a file automatically generated by hipify!!!
#ifndef TH_CUDA_TENSOR_RANDOM_INC
#define TH_CUDA_TENSOR_RANDOM_INC

#include <THH/THHTensor.h>

#include <THH/generic/THHTensorRandom.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensorRandom.h>
#include <THH/THHGenerateBoolType.h>

#endif
